spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shadow_puppets_db?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.14.169.161
    port: 6379
    password: Fuyu742423672

mybatis:
  configuration:
    map-underscore-to-camel-case: true

sms:
  send: false
