spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shadow_puppets_db?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.14.169.161
    port: 6379
    password: Fuyu742423672
  cache:
    cache-names: userDateAnalysis
    couchbase:
      expiration: 3

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 注意：mybatis自带的默认处理器EnumOrdinalTypeHandler 会根据枚举类里值得下标来存储的；如果下标和code不符合，需自定义Handle，我淦！
    # 真实情况建议搞个枚举类的接口，再搞个枚举类统一处理，但是懒得搞了，就这样吧。
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 自定义handle的包
  type-handlers-package: top.fuyuaaa.shadowpuppets.common.mybatis

#是否开启短信发送
sms:
  send: true

alipay:
  server-url: https://openapi.alipaydev.com/gateway.do
  app-id:
  private-key: 
  alipay-public-key:
