spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shadow_puppets_db?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.14.169.161
    port: 6379
    password: Fuyu742423672
  cache:
    cache-names: userDateAnalysis
    couchbase:
      expiration: 3

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 注意：mybatis自带的默认处理器EnumOrdinalTypeHandler 会根据枚举类里值得下标来存储的；如果下标和code不符合，需自定义Handle，我淦！
    # 真实情况建议搞个枚举类的接口，再搞个枚举类统一处理，但是毕设懒得搞了，就这样吧。
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 自定义handle的包
  type-handlers-package: top.fuyuaaa.shadowpuppets.mybatis

#是否开启短信发送
sms:
  send: false

alipay:
  server-url: https://openapi.alipaydev.com/gateway.do
  app-id: 2016093000635581
  private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCGeH40wcaxg9Lx1Fq0F9aicaasJQDDhGg3bpjHlfbMik48dqsn6gR42RWytQjw052pzX7HIpiC2MvHx1crxeCvmlHjyP4Nr+tIpp5UL8oWvIuvxuJ20OYIPnSXA0EjaQNSKcjEiHLLndwxfO/g+mq0LpPo4cjcn/f1J8ecHvCWR5v29EWR+zAGA3ek0GsJ2pEqbTSCz1aP8XnXbPi5iE+2BBv5h4cD2W+PiqWtAGCf0GFvVPI9Qdb8zya0h57Ds6otZAlWuKrnmnAhu4UjOG1wCAlFnHprqmjg61hCcMGWw1+4K0GJjANzEeBzlukxbFaRN5n/EteNOvYoLiSMjHPzAgMBAAECggEAXGsfwj6TwpkpN4+NL01a9JZLyPA9kCLGRaK7WiDVWEqN7rxYcbxCipQYd5Q4qtul9ngHc/FxBCzgEVQNs0XyYH4dXgJbqSiI+ouZMZ8Os4WuM4brSmHUV0Ile0x/Tkj0QVn6ZCirTQoXteN6MhOplmCUw2+6TveawWEvrTsOexmDXXi8zXkIKkuH4+4zZii4+moQjwuUDpfzqPDDfRirUFhzo6oZVgMUEde4dHDKEm7Emn8GreM8LS6x/kI9e9WIZy3xMyPX1uvj6hsz8EjKqGEe6mbCIfsVgoNjupERxQzB2gnD9vOXQgiPUYv20lsYWeGRDBrS6tSVpA3H5xKisQKBgQDllrRKgVsIMkuWHYnFhxfM50N6+WVS5N1XvvuYot/lPmXlNTd6Gh7Ij1lKGbg1KZOG4T50Ct6ILDixxKDqjp2MZok6uFr3I417dE/l6q9diePkM35XEfNSlrmM/jINCAJolq/MxYZeygYw9T/xDk2YTuu5GyE2dsaSeeFnTP6pdwKBgQCV8Jnb/02QVEheNOLejJe8RrE3Q0FTMSeDRLFevJJ5lG9khN+/nZnP5+zSyCqRFrnaQ3+k2fOrqNIGgtINHvXJZ9Wn1sxPgMf/bkfiIYNCbkaRj85tsAH/5hcRhBQTliOyCV/p1+2w/u/fradpovSrVqTjthnObu2bLuCJEW8oZQKBgAzLLRjJxIzcYKHo23iKYqUkbfo4U5Ee98af+d0zlk5r/7maEZFYS0bZ1hvu+vjbbEEj5BsLUAM+k5o0XtMzR0w/mn4PL+J9tLCgdqNVRJhtyqk4xV2MvoZnp8dXkupu+9NgMkOy7h3yHA42XG3OYjyOiUwzWtJyI/adnBXpkHdZAoGASM6G94OV10KFzXDixOwB9gNhpBL9Unco153wfq8UdQL1wBqhRzsw5/qXTZayzLb7Uhe6kILgxnb4XP8DHintcXoBDjnIBcbj1o1nTE+3m/dOPvpUY4C2x9qjUvcOhKA//wB8WWFnYq24LqX1B99/7P7qnEPdbhcBO3xcvVIA5t0CgYAae7wstV04m0Fm3L81Y5/eL/NKo12cumDQRb3y9pD14a0B5bnaLXCCfR0qxUbvpy+gZfDEFeRRJqe+HU/PTiB/WD49D8eL8gLINTZhI3SBZOoUti/LQzw3Esbqgb7yUpT0a2d3mL8bOhe0shgBQvSyaSroa/uSdjXMt3j3Vw7wtQ==
  alipay-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIgHnOn7LLILlKETd6BFRJ0GqgS2Y3mn1wMQmyh9zEyWlz5p1zrahRahbXAfCfSqshSNfqOmAQzSHRVjCqjsAw1jyqrXaPdKBmr90DIpIxmIyKXv4GGAkPyJ/6FTFY99uhpiq0qadD/uSzQsefWo0aTvP/65zi3eof7TcZ32oWpwIDAQAB
